Added GitHub actions for clippy
gussmith23/glenside pull request #170
Opened 2022-03-02 18:27 UTC by RishiKumarRay

Fixed #169

2022-03-02 19:17 UTC, gussmith23 requested changes

2022-03-02 19:17 UTC, gussmith23 commented on .github/workflows/clippy.yml
> +name: Check formatting
```suggestion
name: Run Clippy
```

2022-03-02 19:17 UTC, gussmith23 commented on .github/workflows/clippy.yml
> +  check-formatting:
```suggestion
  run-clippy:
```

2022-03-02 19:17 UTC, gussmith23 commented on .github/workflows/clippy.yml
> +      run: cargo clippy
```suggestion
    - run: cargo clippy
```

2022-03-03 16:45 UTC, RishiKumarRay commented
@gussmith23 please review now

2022-03-03 22:20 UTC, gussmith23 commented
This is great. Thank you so much. I'll merge this soon -- I'm working on another PR right now which I'd like to merge first, and I'd like to fix the errors thrown by clippy before merging this anyway.

Thank you again!

2022-03-03 22:20 UTC, gussmith23 commented
Btw, if you wanted to work on another PR, you could start fixing the issues that clippy is raising!

2022-03-09 19:46 UTC, gussmith23 approved these changes

2022-03-09 19:47 UTC, merged